--SCHEMA--
DROP TABLE IF EXISTS snapsevise;

CREATE TABLE snapsevise (
    snapseviseId INT AUTO_INCREMENT PRIMARY KEY,
    snapseviseRim VARCHAR
);

--INIT DATA--
INSERT INTO snapsevise (snapseviseId, snapseviseRim) VALUES
                                                         (1, 'vi skal gausseliminere, og vores lem skal oscillere'),
                                                         (2, 'en der kilder lidt i klitten, en der hiver i banditten'),
                                                         (3, 'beviserne blir’ svære at lære, så nu skal du drikke mere'),
                                                         (4, 'teoremer korrolarer, fuck nu det vi drikker bare'),
                                                         (5, 'steen og marianne snakker, 40 sekunder med din makker'),
                                                         (6, 'en person skal drikke bajer, dette vælges når i peger'),
                                                         (7, 'jeg vil gerne score din fætter, han er bare mega lækker'),
                                                         (8, 'infralumen supersokinsk det er mega fucking komisk'),
                                                         (9, 'vi skal være pisse stive for det ka vi nemlig blive'),
                                                         (10, 'lauras sommersby faldt nedad og på floor skal det gå nedaf'),
                                                         (11, 'sune bærer rundt på naoh, og han har en kæmpe boa(eller mega lækker tarmflora)'),
                                                         (12, 'klorhexidin(eller andre former for behandling) skal du bruge, ellers døden den kan true'),
                                                         (13, 'vibes lighter har en fatflame, men man må jo ikke fatshame'),
                                                         (14, 'laura kan ik ramme skrælder’n, det er bare mega trællern'),
                                                         (15, 'nu vi blevet pisse stive, jeg kan ikke rime mere'),
                                                         (16, 'i blok 3 vi bæller sauvignon, mens vi koder lidt i pythón'),
                                                         (17, 'frøer de er sød’ og flotte, de er gode til at hoppe'),
                                                         (18, 'træstammer kan li at ligge, for at stå det kan de ikke'),
                                                         (19, 'du er bare en der yapper, du skal flette dine flapper'),
                                                         (20, 'ida hun ka godt li tie dye, så vi giver hende sideeye'),
                                                         (21, 'volt og watt og elektroner, det gir mig en kæmpe boner'),
                                                         (22, 'vi bestod første semester, så nu ska vi holde fester'),
                                                         (23, 'vi er færdi’ med eksamen så nu skal jeg hjem til damen'),
                                                         (24, 'gausskurver usikkerheder, det er bare super nedern'),
                                                         (25, 'mej nej nej nej det skal vi ej'),
                                                         (26, 'nej nej nej det sjal vi ikke, men på laura skal vi slikke'),
                                                         (27, 'nu vi blevet meget stive, vi kan ikke rime mere'),
                                                         (28, 'vi skal ik’ ha julesteeg, fordi vi er midt i maaj'),
                                                         (29, 'Vi skal ud og drikke vand vi er herre stive mand'),
                                                         (30, 'vibe nangler sine briller, det derfor hun går og falder'),
                                                         (31, 'laura hun skal ud at bade, hun må ik få remoulade'),
                                                         (32, 'jeg vil gerne op i bad for så ka jeg blive glad'),
                                                         (33, 'laura skal vaske sine hæner og børst sune tænder'),
                                                         (34, 'di skal holde din fucking kæft ellers bliver du en hest'),
                                                         (35, 'em1 og em2, vi ska være stive nuu'),
                                                         (36, 'en og to og tre og fire, fem og sex og syv og otte'),
                                                         (37, 'integraler ka vi ikke men til gengæld ka vi drikke'),
                                                         (38, 'anup han ka li sit liv fordi han ka drik sig stiv'),
                                                         (39, 'Mig jeg drikker due shots og de smager mega godt'),
                                                         (40, 'Det er bare helt i orden fordi at du hedder morten'),
                                                         (41, 'a og be og ce og dee, g og ef og e og ii'),
                                                         (42, 'keg vil gerne spise maling og du er en fucking kælling'),
                                                         (43, 'anup mister alt sit håår derfor håber vi han gåår'),
                                                         (44, 'jeg vil gerne hæng mig seelv så nu siger jeg farvel'),
                                                         (45, 'vi har cirkulær balance vi skal hjem i ambulance'),
                                                         (46, 'hapd haps haps….. snaps'),
                                                         (47, 'anup han er mega klaam jeg sys han skal skifte haam'),
                                                         (48, 'anup ligter rigtig sleemt indien vil ha ham hjeem'),
                                                         (49, 'anup lugter lidt a pruut fordi hans numse er kapuut'),
                                                         (50, 'tænke tænke tænke tænke, tænke tænke tænle tænke'),
                                                         (51, 'anup skal fucking aflives fordi han kan ik tilgives'),
                                                         (52, 'mig jeg hænger lige mig seelv jeg vil slå mig selv ihjeel'),
                                                         (53, 'anup han er fucking trashy fordu han ryr meget hashy'),
                                                         (54, 'anjp skal på intensiv fordi han er fjcning stiv'),
                                                         (55, 'alura hun r fucking fulder hun ka ik li mænd med muller'),
                                                         (56, 'lauda hun er mega floot fordi hun er kæmpe sluut'),
                                                         (57, 'anup han er fucking duum derfor skal han hole sin muund'),
                                                         (58, 'jeg skal fucking ik til amar’ for så kommer de og tar mig'),
                                                         (59, 'anup han kan ikke regne han er fucking nem at tegne'),
                                                         (60, 'laura hun har slukket solen hun fortjener kongestolen'),
                                                         (61, 'laura hun må ikke flexe fpr så bæir hun såist af hejse'),
                                                         (62, 'Nup lugter lidt sf ost og jeg briget ham domkpst'),
                                                         (63, 'lairs r dum som en steen og jeg beækker jendes been'),
                                                         (64, 'man må ik slå vibe ihjel for hun har em dejlig skæl'),
                                                         (65, 'anup han ka drikke bajer derfor tar han nogle streger'),
                                                         (66, 'aura r allerede stiiv hun når aldrig hjem i liive'),
                                                         (67, 'det er pride nu i dag de derfor de hejser flag'),
                                                         (68, 'laura hun skal trække vejret ellers blir hun maselreret'),
                                                         (69, 'du må ikke gå for hurtigt for så har du ik en stor pik'),
                                                         (70, 'vi skal i wn fucking netto fordi vi bor i en ghettp'),
                                                         (71, 'anup hn t fucking hrim pg jeg flækker bar hans tand'),
                                                         (72, 'amyp han går og spilder for han hat en lille diller'),
                                                         (73, 'man skal amtid respnere ellers bæir man slæet mere'),
                                                         (74, 'maura jeg vil slå dig need ellers blir du til en geed'),
                                                         (75, 'biler kører på benzin, men anup han kør’ på vin(jeg vil hellere kør’ på vin)'),
                                                         (76, 'laura hun ka li at snøvle hun skal sparkes med en støvle'),
                                                         (77, 'vibe hun er fucking dejlig hens emoji er en smiley'),
                                                         (78, 'anup mister alt dit gåår fordi han var stiv igååår'),
                                                         (79, 'lauea hun har drukkket bajer fordi hun skal fucking fekre'),
                                                         (80, 'jeg vil bsre gerne kome mp jeg gør det i din lomme'),
                                                         (81, 'anup han skal fickign dø han må hippei en sø'),
                                                         (82, 'anup han er krimineæ derfor skal han hænge sig selv'),
                                                         (83, 'laura er en kæmpe fangst selvom hun har meget angst'),
                                                         (84, 'fjoller kigger på mobil han tar mthamfetamin'),
                                                         (85, 'fjollers forækdre er døve derfor blev han født som løve'),
                                                         (86, 'vibe har ik stræm tilbage men hjn skriver hvad laua sagde'),
                                                         (87, 'ind r ik i snapsevise derfor han skal fucking spise'),
                                                         (88, 'laura hun skal fucking tænke jeg sætter hebd k en lænke'),
                                                         (89, 'matmatik r i aud 1 der hvos vine har fået pik'),
                                                         (90, 'laura er en drillepind men hun har et dejligt sind'),
                                                         (91, 'julefrokost skal vi spise vi skal syng en snapsevise'),
                                                         (92, 'vi ka godt li astro et især når vi må drikke lidt'),
                                                         (93, 'astro to det la vi li jeg vil slikke på et li - nej det må man altså ikke man må heller slik på pikke'),
                                                         (94, 'vibe drikker meget te hun burde gå rundt med ble'),
                                                         (95, 'laura du gir mig psykose du skal i en skraldepose'),
                                                         (96, 'jeg sys du er meget fræk selvom du lugter lidt af bræk'),
                                                         (97, 'laura er en salamander hun ka nemlig li at blande sig'),
                                                         (98, 'jeg ka godt li når du smirker det gør at jeg fucking squirter'),
                                                         (99, 'laura er en lil delfin det fordi hun drikker vin'),
                                                         (100, 'min pik den er meget kort lige så kort som vibe hjorth'),
                                                         (101, 'anup han er fucking lam derfor skal man bide ham😈😈'),
                                                         (102, 'laura hun ka godt li stier men hun ka kun rim’ på piger'),
                                                         (103, 'jeg sys det car fucking dråben men cafeen? den er åben'),
                                                         (104, 'jeg sys laura hun er grum fordi hun ga’ mig sit skum(😏😏💦💦)'),
                                                         (105, 'anup er ik særlig klog han sku til at læs en bog'),
                                                         (106, 'hun blir locked out i en ige fordi hun ka li at suge'),
                                                         (107, 'det fordi at vi var stove det var ikke svært at blive'),
                                                         (108, 'anup han er ficking tarvelig han skal have tæsk tiæ daglig'),
                                                         (109, 'laura hun tar amf til hevrdag ellers dumper hun alle fag'),
                                                         (110, 'laura hun skal fucking skide og det sys hun vi skal vide'),
                                                         (111, 'laura hun ka ki at drikke men hun burde hellere strikke');